version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.10
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.2
    - 3.25.3
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.1
    - 7.26.2
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.1
    - 5.3.2
    - 5.6.2
    - 5.6.5
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.1
    - 3.25.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: jquery
    versions:
    - 3.5.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: ember-cli-htmlbars-inline-precompile
    versions:
    - 3.0.1
